Reward Pools:  
  Trinkets:
    APPLE: 3
    BAKED_POTATO: 6
    BED: 3
    BEETROOT: 1 
    BEETROOT_SOUP: 1
    BLAZE_POWDER: 4
    BOAT: 5
    BONE: 10
    BOOK: 6
    BOOKSHELF: 1
    BREAD: 2
    BRICK: 4
    BUCKET: 2
    CAKE: 1
    CLAY: 2
    CLAY_BALL: 8  
    COAL: 8
    COBBLESTONE: 45
    COMPASS: 3
    COOKED_BEEF: 2
    COOKED_CHICKEN: 2
    COOKED_FISH: 2
    COOKED_RABBIT: 1
    COOKIE: 5
    DARK_OAK_DOOR: 5
    DEAD_BUSH: 15
    DIODE: 4
    EGG: 3
    ENDER_PEARL: 1
    FEATHER: 10
    FENCE: 10
    FENCE_GATE: 2
    FERMENTED_SPIDER_EYE: 4
    FISHING_ROD: 5
    FLINT: 10
    FLINT_AND_STEEL: 2
    FLOWER_POT_ITEM: 5
    FURNACE: 5
    GHAST_TEAR: 1
    GLASS: 10
    GLASS_BOTTLE: 10
    GLOWSTONE_DUST: 2
    GRAVEL: 15
    HAY_BLOCK: 4
    IRON_INGOT: 6
    IRON_LEGGINGS: 2
    IRON_SWORD: 3
    JACK_O_LANTERN: 12
    LADDER: 5
    LEATHER: 5
    LEATHER_BOOTS: 20
    LEATHER_HELMET: 10
    LEVER: 8
    LOG: 10
    LONG_GRASS: 15
    MAGMA_CREAM: 3
    MINECART: 1
    MOSSY_COBBLESTONE: 5
    NETHER_BRICK: 5
    NETHER_BRICK_ITEM: 15
    NETHERRACK: 18
    NOTE_BLOCK: 5
    OBSIDIAN: 1
    PAPER: 10
    POISONOUS_POTATO: 20
    PUMPKIN_PIE: 3
    QUARTZ: 2
    RABBIT: 6
    REDSTONE: 30
    SAND: 15
    SHEARS: 1
    SIGN: 15
    SLIME_BALL: 8
    SNOW_BALL: 15
    STICK: 15
    STONE: 30
    STONE_SWORD: 15
    STRING: 10
    SUGAR: 15
    SULPHUR: 8
    VINE: 8
    WATCH: 1
    WATER_LILY: 3
    WHEAT: 35
    WOOD: 30
    WOOD_HOE: 20
    WOOL: 15
  
  
  