name: EverydayMiracles
main: io.github.Oranitha.EverydayMiracles.EverydayMiracles
version: 0.0.1
author: Oranitha

commands:
  edm:
    description: Base command for EverydayMiracles
    permission: everydaymiracles.worship
    permission-message: You can’t use this command, you don't have the permission <permission>!

  edm follow:
    description: List available leaders
    permission: everydaymiracles.worship
    permission-message: You can’t use this command, you don't have the permission 

  edm follow [leader]:
    description: Follow specified leader
    permission: everydaymiracles.worship
    permission-message: You can’t use this command, you don't have the permission 

  edm quest:
    description: Receive a quest from your leader

  edm chat:
    description: Receive a message from your leader

  edm enquire:
    description: Get info about your current quest

  edm points:
    description: Get the number of points you’ve earned

  edm submit:
    description: Submit a quest for completion

  edma:
    description: Base command for EDM admin tasks.
    permission: everydaymiracles.admin
    permission-message: You can’t use this command, you don't have the permission <permission>!

  edma givePoints:
    description: /givePoints <player> <amount>. Takes negatives.

  edma setDeity:
    description: /setDeity <player> <deity>


permissions:
  everydaymiracles.worship:
    description: Allows you to use basic features of EverydayMiracles, such as following leaders and requesting assistance.
    default: true

  everydaymiracles.admin:
    description: Allows you to use advanced admin commands, such as giving players reward points and removing a player’s follower status.
    default: op 
